// V2-G wave 5 (docs/MASTER_ROADMAP.md: "Provide capability-aware actions and
// compatible Agent upgrades for the selected host matrix"): the Linux twin of
// the Windows Local Agent update flow. A running agent cannot reliably replace
// its own runtime, so the update is staged next to the live runtime and a
// short-lived `systemd-run --user` transient unit performs the swap after the
// agent has exited: stop unit -> rename the current runtime to the backup
// path -> atomically rename the staged runtime into place -> restart the unit.
// Any failure after the backup rename restores the backup before restarting so
// the agent comes back on the previous runtime (the Windows scheduled-task
// swap pattern's Linux twin).
//
// The post-exit swap itself is pure sh + mv + systemctl on purpose: the script
// runs when the runtime it replaces may be mid-swap, so it must not depend on
// Node or the agent. swapLinuxAgentRuntime() implements the identical ordering
// in Node so the smoke can pin the backup-before-swap and rollback semantics
// hermetically; the generated script and this function are the same ordered
// steps and both are covered by scripts/agent-self-update-smoke.js.
//
// Every external command goes through execFile with a timeout, and the
// orchestrator accepts injected seams (command executor, copy tree, rename,
// clock, sleep) the same way the agent's restartScheduleService does, so the
// smoke runs hermetically on any host without systemd.

const { execFile } = require("child_process");
const fs = require("fs");
const path = require("path");

const LINUX_AGENT_UNIT_NAME = "anxos-agent.service";
const DEFAULT_AGENT_ENTRYPOINT = path.join("agent", "src", "server.js");
const DEFAULT_SWAP_TIMEOUT_MS = 60000;
const DEFAULT_RESTART_POLL_ATTEMPTS = 5;
const DEFAULT_RESTART_POLL_DELAY_MS = 300;

// Canonical ordered plan. Callers surface these ids in progress reporting.
const UPDATE_PLAN_STEP_IDS = ["verify", "stage", "schedule-swap", "swap", "restart", "record"];

// Status markers the generated post-exit swap script writes to the result
// file. The orchestrator maps them to step outcomes; only COMPLETE continues.
const SWAP_STATUS = {
  COMPLETE: "complete",
  FAILED_MISSING_STAGED: "failed-missing-staged",
  FAILED_BACKUP: "failed-backup",
  FAILED_PUBLISH: "failed-publish",
  FAILED_ROLLED_BACK: "failed-rolled-back",
  FAILED_RESTART: "failed-restart",
};

function updateStep(id, label, state = "pending", message = "") {
  return { id, label, state, message, at: new Date().toISOString() };
}

function buildLinuxAgentUpdatePlan(labels = {}) {
  const defaultLabels = {
    verify: "Validate live runtime and pinned source",
    stage: "Stage pinned runtime with temp+rename",
    "schedule-swap": "Schedule post-exit swap unit",
    swap: "Swap runtime after agent exit",
    restart: "Restart systemd unit",
    record: "Record update outcome",
  };
  return UPDATE_PLAN_STEP_IDS.map((id) => updateStep(id, labels[id] || defaultLabels[id]));
}

function shQuote(value) {
  return `'${String(value).replace(/'/g, `'\\''`)}'`;
}

function assertSwapScriptInput(options) {
  for (const key of ["runtimeRoot", "stagedRoot", "backupRoot", "resultPath"]) {
    if (!String(options[key] || "").trim()) {
      throw Object.assign(new Error(`The post-exit swap script requires ${key}.`), { code: "LINUX_SWAP_SCRIPT_INVALID" });
    }
  }
}

function buildPostExitSwapScript({ unitName = LINUX_AGENT_UNIT_NAME, runtimeRoot, stagedRoot, backupRoot, resultPath }) {
  assertSwapScriptInput({ runtimeRoot, stagedRoot, backupRoot, resultPath });
  return [
    "#!/bin/sh",
    `# AnxOS Linux Agent post-exit swap for ${unitName}, generated by src/shared/linuxAgentSelfUpdate.js.`,
    "# Ordering is load-bearing: stop the agent, move the current runtime to the",
    "# backup path, atomically rename the staged runtime into place, then restart.",
    "# Any failure after the backup rename restores the backup before restarting",
    "# so the agent comes back on the previous runtime.",
    "set -u",
    `UNIT=${shQuote(unitName)}`,
    `RUNTIME=${shQuote(runtimeRoot)}`,
    `STAGED=${shQuote(stagedRoot)}`,
    `BACKUP=${shQuote(backupRoot)}`,
    `RESULT=${shQuote(resultPath)}`,
    "",
    'systemctl --user stop "$UNIT" >/dev/null 2>&1 || true',
    "",
    'if [ ! -d "$STAGED" ]; then',
    `  printf '%s\\n' ${shQuote(SWAP_STATUS.FAILED_MISSING_STAGED)} > "$RESULT"`,
    "  exit 1",
    "fi",
    "",
    'if [ -d "$RUNTIME" ]; then',
    '  if ! mv "$RUNTIME" "$BACKUP"; then',
    `    printf '%s\\n' ${shQuote(SWAP_STATUS.FAILED_BACKUP)} > "$RESULT"`,
    "    exit 1",
    "  fi",
    '  if ! mv "$STAGED" "$RUNTIME"; then',
    '    mv "$BACKUP" "$RUNTIME" || true',
    '    systemctl --user start "$UNIT" >/dev/null 2>&1 || true',
    `    printf '%s\\n' ${shQuote(SWAP_STATUS.FAILED_ROLLED_BACK)} > "$RESULT"`,
    "    exit 1",
    "  fi",
    "else",
    '  if ! mv "$STAGED" "$RUNTIME"; then',
    `    printf '%s\\n' ${shQuote(SWAP_STATUS.FAILED_PUBLISH)} > "$RESULT"`,
    "    exit 1",
    "  fi",
    "fi",
    "",
    'if ! systemctl --user start "$UNIT"; then',
    `  printf '%s\\n' ${shQuote(SWAP_STATUS.FAILED_RESTART)} > "$RESULT"`,
    "  exit 1",
    "fi",
    `printf '%s\\n' ${shQuote(SWAP_STATUS.COMPLETE)} > "$RESULT"`,
    "",
  ].join("\n");
}

// Node mirror of the generated swap script (see the header comment). `rename`
// is a seam so the smoke can fail the publish step deterministically instead
// of racing a real filesystem.
function swapLinuxAgentRuntime({ runtimeRoot, stagedRoot, backupRoot, rename = (from, to) => fs.renameSync(from, to) }) {
  if (!String(runtimeRoot || "").trim() || !String(stagedRoot || "").trim() || !String(backupRoot || "").trim()) {
    throw Object.assign(new Error("The runtime swap requires runtimeRoot, stagedRoot and backupRoot."), { code: "LINUX_AGENT_SWAP_INVALID_OPTIONS" });
  }
  if (!fs.existsSync(stagedRoot)) {
    throw Object.assign(new Error("Staged runtime is missing; the swap was refused before the previous runtime was touched."), {
      code: "LINUX_AGENT_SWAP_STAGED_MISSING",
      rolledBack: false,
    });
  }
  if (fs.existsSync(runtimeRoot)) {
    try {
      rename(runtimeRoot, backupRoot);
    } catch (error) {
      throw Object.assign(new Error(`The previous runtime could not be moved to the backup path: ${error.message}`), {
        code: "LINUX_AGENT_SWAP_BACKUP_FAILED",
        cause: error,
        rolledBack: false,
      });
    }
    try {
      rename(stagedRoot, runtimeRoot);
    } catch (error) {
      try {
        rename(backupRoot, runtimeRoot);
      } catch (rollbackError) {
        throw Object.assign(new Error(`The staged runtime could not be published and the backup could not be restored: ${rollbackError.message}`), {
          code: "LINUX_AGENT_SWAP_ROLLBACK_FAILED",
          cause: error,
          backupRoot,
          rolledBack: false,
        });
      }
      throw Object.assign(new Error("The staged runtime could not be published; the previous runtime was restored from the backup."), {
        code: "LINUX_AGENT_SWAP_FAILED",
        cause: error,
        backupRoot,
        rolledBack: true,
      });
    }
  } else {
    try {
      rename(stagedRoot, runtimeRoot);
    } catch (error) {
      throw Object.assign(new Error(`The staged runtime could not be published: ${error.message}`), {
        code: "LINUX_AGENT_SWAP_FAILED",
        cause: error,
        rolledBack: false,
      });
    }
  }
  return { swapped: true, backupPreserved: fs.existsSync(backupRoot) };
}

// Stage the pinned runtime as a sibling of the live runtime so every later
// rename stays on one filesystem (rename(2) is only atomic within a device).
// The tree is copied to a temp sibling, verified, then atomically renamed to
// the final staging path — a partially copied tree is never publishable.
function stageLinuxAgentRuntime({ sourceRoot, runtimeRoot, entrypoint = DEFAULT_AGENT_ENTRYPOINT, copyTree = (from, to) => fs.cpSync(from, to, { recursive: true }), now = Date.now, pid = process.pid }) {
  if (!fs.existsSync(path.join(sourceRoot, entrypoint))) {
    throw Object.assign(new Error(`The pinned runtime source does not contain the Agent entrypoint (${entrypoint}).`), {
      code: "LINUX_AGENT_RUNTIME_SOURCE_MISSING",
      sourceRoot,
    });
  }
  const stamp = new Date(now()).toISOString().replace(/[:.]/g, "-");
  const stagedRoot = `${runtimeRoot}.update-${stamp}`;
  const tempRoot = `${stagedRoot}.tmp-${pid}`;
  try {
    fs.mkdirSync(path.dirname(tempRoot), { recursive: true });
    copyTree(sourceRoot, tempRoot);
    if (!fs.existsSync(path.join(tempRoot, entrypoint))) {
      throw Object.assign(new Error("The staged tree did not contain the Agent entrypoint; publish refused."), { code: "LINUX_AGENT_STAGE_INVALID" });
    }
    fs.renameSync(tempRoot, stagedRoot);
    return { stagedRoot, stamp };
  } catch (error) {
    try {
      fs.rmSync(tempRoot, { recursive: true, force: true });
    } catch {
      // Best-effort cleanup; the staged path was never published.
    }
    if (error.code === "LINUX_AGENT_RUNTIME_SOURCE_MISSING" || error.code === "LINUX_AGENT_STAGE_INVALID") throw error;
    throw Object.assign(new Error(`The pinned runtime could not be staged: ${error.message}`), {
      code: "LINUX_AGENT_STAGE_FAILED",
      cause: error,
    });
  }
}

function verifyUpdateInputs({ runtimeRoot, sourceRoot, entrypoint }) {
  if (!fs.existsSync(path.join(sourceRoot, entrypoint))) {
    throw Object.assign(new Error(`The pinned runtime source does not contain the Agent entrypoint (${entrypoint}).`), {
      code: "LINUX_AGENT_RUNTIME_SOURCE_MISSING",
      sourceRoot,
    });
  }
  if (!fs.existsSync(path.join(runtimeRoot, entrypoint))) {
    throw Object.assign(new Error(`The live Agent runtime does not contain the Agent entrypoint (${entrypoint}).`), {
      code: "LINUX_AGENT_RUNTIME_ROOT_INVALID",
      runtimeRoot,
    });
  }
  try {
    fs.accessSync(path.dirname(runtimeRoot), fs.constants.W_OK);
  } catch (error) {
    throw Object.assign(new Error("The Agent runtime directory is not writable by the current user, so the runtime cannot be swapped without elevated help."), {
      code: "LINUX_AGENT_RUNTIME_ROOT_NOT_WRITABLE",
      cause: error,
      runtimeRoot,
    });
  }
}

function defaultRunCommand(file, args, options = {}) {
  return new Promise((resolve) => {
    execFile(file, args, { windowsHide: true, timeout: options.timeoutMs || 30000, maxBuffer: 256 * 1024 }, (error, stdout, stderr) => {
      resolve({ ok: !error, code: error?.code ?? null, stdout: String(stdout || "").trim(), stderr: String(stderr || "").trim(), timedOut: Boolean(error?.killed) });
    });
  });
}

function readSwapResult(resultPath) {
  try {
    const value = String(fs.readFileSync(resultPath, "utf8")).trim();
    return Object.values(SWAP_STATUS).includes(value) ? value : `unknown:${value.slice(0, 80)}`;
  } catch {
    return null;
  }
}

function writeLinuxUpdateRecord(updateDir, record) {
  const filePath = path.join(updateDir, "last-linux-update.json");
  fs.writeFileSync(filePath, `${JSON.stringify({ ...record, updatedAt: new Date().toISOString() }, null, 2)}\n`, { mode: 0o600 });
  return filePath;
}

// Orchestrates one Linux agent runtime update. Seams (runCommand, copyTree,
// rename, now, sleep, onScheduled) are injectable for hermetic tests; in
// production only the defaults run. `onScheduled` fires right before the
// transient unit is scheduled with the swap artifacts, so callers can log or
// (in tests) simulate the unit.
async function runLinuxAgentSelfUpdate(options = {}) {
  const {
    runtimeRoot,
    sourceRoot,
    sourceVersion,
    installedVersion = null,
    updateDir,
    unitName = LINUX_AGENT_UNIT_NAME,
    entrypoint = DEFAULT_AGENT_ENTRYPOINT,
    reason = "linux-agent-update",
    swapTimeoutMs = DEFAULT_SWAP_TIMEOUT_MS,
    restartPollAttempts = DEFAULT_RESTART_POLL_ATTEMPTS,
    restartPollDelayMs = DEFAULT_RESTART_POLL_DELAY_MS,
    runCommand = defaultRunCommand,
    copyTree,
    now = Date.now,
    sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms)),
    onScheduled = null,
  } = options;

  for (const key of ["runtimeRoot", "sourceRoot", "updateDir"]) {
    if (!String(options[key] || "").trim()) {
      throw Object.assign(new Error(`Linux Agent self-update requires ${key}.`), { code: "LINUX_AGENT_UPDATE_INVALID_OPTIONS" });
    }
  }

  fs.mkdirSync(updateDir, { recursive: true });
  const steps = buildLinuxAgentUpdatePlan();
  const mark = (id, state, message) => {
    const step = steps.find((entry) => entry.id === id);
    if (step) {
      step.state = state;
      if (message) step.message = message;
      step.at = new Date().toISOString();
    }
    return step;
  };
  const stamp = new Date(now()).toISOString().replace(/[:.]/g, "-");
  const scriptPath = path.join(updateDir, `swap-${stamp}.sh`);
  const resultPath = path.join(updateDir, `swap-${stamp}.result`);
  const backupRoot = `${runtimeRoot}.backup-${stamp}`;
  let stagedRoot = null;

  const fail = (code, message, details = {}) => Object.assign(new Error(message), { code, details, steps });
  const writeFailureRecord = (error) => {
    try {
      return writeLinuxUpdateRecord(updateDir, {
        reason,
        mechanism: "linux-systemd",
        unitName,
        fromVersion: installedVersion,
        toVersion: sourceVersion || null,
        runtimeRoot,
        backupRoot,
        stagedRoot,
        scriptPath,
        resultPath,
        status: "failed",
        error: { code: error.code || "LINUX_AGENT_UPDATE_FAILED", message: error.message },
      });
    } catch {
      return null;
    }
  };

  try {
    verifyUpdateInputs({ runtimeRoot, sourceRoot, entrypoint });
    mark("verify", "complete", `Live runtime and pinned source validated (pinned version ${sourceVersion || "unknown"}).`);

    const staged = stageLinuxAgentRuntime({ sourceRoot, runtimeRoot, entrypoint, ...(copyTree ? { copyTree } : {}), now });
    stagedRoot = staged.stagedRoot;
    mark("stage", "complete", `Pinned runtime staged at ${stagedRoot} via temp+rename.`);

    fs.writeFileSync(scriptPath, buildPostExitSwapScript({ unitName, runtimeRoot, stagedRoot, backupRoot, resultPath }), { mode: 0o700 });
    if (typeof onScheduled === "function") {
      onScheduled({ scriptPath, resultPath, stagedRoot, backupRoot, unitName });
    }
    const schedule = await runCommand(
      "systemd-run",
      ["--user", "--unit", `anxos-agent-update-${stamp}`, "--collect", "--wait", "/bin/sh", scriptPath],
      { timeoutMs: swapTimeoutMs },
    );
    if (!schedule.ok) {
      if (schedule.timedOut) {
        // The transient unit may still be mid-swap; the record names the
        // script, result file and backup path an operator needs.
        throw fail("LINUX_AGENT_SWAP_TIMEOUT", "The post-exit swap unit did not finish before the timeout. Inspect `journalctl --user -u anxos-agent-update` and the update record before retrying.", { scriptPath, resultPath, backupRoot, stagedRoot });
      }
      throw fail("LINUX_AGENT_SWAP_SCHEDULE_FAILED", schedule.stderr || schedule.stdout || "systemd-run could not schedule the post-exit swap unit.", { scriptPath, stagedRoot, backupRoot, exitCode: schedule.code });
    }
    mark("schedule-swap", "complete", `Post-exit swap scheduled on ${unitName} (backup-before-swap ordering).`);

    const swapStatus = readSwapResult(resultPath);
    if (!swapStatus) {
      throw fail("LINUX_AGENT_SWAP_OUTCOME_UNKNOWN", "The post-exit swap unit finished without writing a result marker. Inspect `journalctl --user` and the update record before retrying.", { scriptPath, resultPath, backupRoot, stagedRoot });
    }
    if (swapStatus !== SWAP_STATUS.COMPLETE) {
      const rolledBack = swapStatus === SWAP_STATUS.FAILED_ROLLED_BACK;
      mark("swap", "failed", rolledBack
        ? `The swap failed and the previous runtime was restored from ${backupRoot}.`
        : `The swap failed (${swapStatus}); the previous runtime backup is at ${backupRoot}.`);
      throw fail("LINUX_AGENT_SWAP_FAILED", `The post-exit swap failed (${swapStatus}).`, { swapStatus, rolledBack, backupRoot, stagedRoot, scriptPath });
    }
    mark("swap", "complete", `Previous runtime preserved at ${backupRoot}; the staged runtime was published with an atomic rename.`);

    mark("restart", "running", `Waiting for ${unitName} to become active on the updated runtime.`);
    let active = false;
    let lastProbe = null;
    for (let attempt = 0; attempt < restartPollAttempts; attempt += 1) {
      if (attempt > 0) await sleep(restartPollDelayMs);
      lastProbe = await runCommand("systemctl", ["--user", "is-active", unitName], { timeoutMs: 10000 });
      if (lastProbe.ok && String(lastProbe.stdout || "").trim() === "active") {
        active = true;
        break;
      }
    }
    if (!active) {
      throw fail("LINUX_AGENT_RESTART_VERIFY_FAILED", `${unitName} did not become active after the swap.`, {
        stdout: lastProbe?.stdout || null,
        stderr: lastProbe?.stderr || null,
        backupRoot,
      });
    }
    mark("restart", "complete", `${unitName} is active on the updated runtime.`);

    const recordPath = writeLinuxUpdateRecord(updateDir, {
      reason,
      mechanism: "linux-systemd",
      unitName,
      fromVersion: installedVersion,
      toVersion: sourceVersion || null,
      runtimeRoot,
      backupRoot,
      stagedRoot,
      scriptPath,
      resultPath,
      status: "complete",
    });
    mark("record", "complete", `Update outcome recorded at ${recordPath}.`);

    return {
      ok: true,
      swapped: true,
      mechanism: "linux-systemd",
      unitName,
      pinnedVersion: sourceVersion || null,
      installedVersion,
      stagedRoot,
      backupRoot,
      scriptPath,
      resultPath,
      recordPath,
      steps,
    };
  } catch (error) {
    error.steps = error.steps || steps;
    const recordPath = writeFailureRecord(error);
    if (recordPath) error.recordPath = recordPath;
    throw error;
  }
}

module.exports = {
  DEFAULT_AGENT_ENTRYPOINT,
  LINUX_AGENT_UNIT_NAME,
  SWAP_STATUS,
  UPDATE_PLAN_STEP_IDS,
  buildLinuxAgentUpdatePlan,
  buildPostExitSwapScript,
  runLinuxAgentSelfUpdate,
  stageLinuxAgentRuntime,
  swapLinuxAgentRuntime,
};
